name: Deploy to NuGet

on:
  workflow_dispatch:  # Manueller Trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal
        
    - name: Increment version numbers
      run: |
        # ... (dein bestehendes Skript zur Versionsinkrementierung)

    - name: Build and Pack
      run: |
        dotnet build --configuration Release
        dotnet pack --no-build -c Release -o out

    - name: Push new version
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add TablerForNet.csproj
        git commit -m "Increment version to $NEW_VERSION"
        git push origin master
      
    - name: Push to NuGet
      run: dotnet nuget push out/*.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
