name: .NET

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'  # Checkt Submodule rekursiv aus

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    # Increase Version number
    - name: Bump version
      run: |
        cd TablerForNet
        version=$(grep -oP '<Version>\K(.*)(?=<)' TablerForNet.csproj)
        IFS='.' read -ra PARTS <<< "$version"
        new_version="${PARTS[0]}.${PARTS[1]}.${PARTS[2]}.$((PARTS[3] + 1))"
        sed -i "s|<Version>$version</Version>|<Version>$new_version</Version>|g" TablerForNet.csproj
      shell: bash

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    # Commit changes
    - name: Commit and push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Bump version"
        git push https://${{secrets.BUMPVERSIONTOKEN}}@github.com/Nix1983/TablerForNet.git
