# .github/workflows/auto-increment-version.yml
name: Auto Increment Version

on:
  push:
    branches:
      - master  # Trigger when pushed to master branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.x'  # Update to your project's .NET version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Increment version number
      run: |
        # Retrieve the old version number from your .csproj file
        OLD_VERSION=$(grep -oP '(?<=<Version>).*?(?=</Version>)' TablerForNet.csproj)
        
        # Increment the version number (You can adjust the logic as needed)
        NEW_VERSION=$(echo $OLD_VERSION | awk -F. '{$NF++; OFS="."; print $0}')

        # Update the .csproj file with the new version
        sed -i "s/<Version>$OLD_VERSION<\/Version>/<Version>$NEW_VERSION<\/Version>/" TablerForNet.csproj

    - name: Push new version
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add TablerForNet.csproj
        git commit -m "Increment version to $NEW_VERSION"
        git push https://x-access-token:${{ secrets.BUMPVERSIONTOKEN }}@github.com/Nix1983/TablerForNet.git

